name       : libgit2-glib
version    : 0.22.8
release    : 1
source     :
    - http://ftp.gnome.org/pub/gnome/sources/libgit2-glib/0.22/libgit2-glib-0.22.8.tar.xz : 05c9453b195f1af0df2a5d8bc71472c9fb26d14bb8fbb5b688ad1b8ef7a30959
license    : LGPL-2.1
summary    : libgit2-glib is a glib wrapper library around the libgit2 git access library.
description: |
    libgit2-glib is a glib wrapper library around the libgit2 git access library.
builddeps  :
  - gnome-common
  - glib2
  - pkgconfig(gio-2.0)
  - gobject-introspection
  - libgit2-devel
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install