name       : libgit2-glib
version    : 0.28.0.1
release    : 31
source     :
    - https://download.gnome.org/sources/libgit2-glib/0.28/libgit2-glib-0.28.0.1.tar.xz : e70118481241a841d5261bdd4caa3158b2ffcb5ccf9d4f32b6cf6563b83a0f28
license    : LGPL-2.1-or-later
component  : programming.library
summary    : libgit2-glib is a glib wrapper library around the libgit2 git access
    library.
description: |
    libgit2-glib is a glib wrapper library around the libgit2 git access library.
patterns   :
    - docs : [/usr/share/doc]
builddeps  :
    - pkgconfig(gio-2.0)
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(libgit2)
    - pkgconfig(libssh2)
    - pkgconfig(openssl)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(python3)
    - gnome-common
    - gtk-doc
    - vala
setup      : |
    %meson_configure -Dgtk_doc=true
build      : |
    %ninja_build
install    : |
    %ninja_install
    mv $installdir/usr/share/vala $installdir/usr/share/vala-0.46
