name       : libgit2-glib
version    : 0.26.2
release    : 26
source     :
    - https://download.gnome.org/sources/libgit2-glib/0.26/libgit2-glib-0.26.2.tar.xz : 2ad6f20db2e38bbfdb6cb452704fe8a911036b86de82dc75bb0f3b20db40ce9c
license    : LGPL-2.1
component  : programming.library
summary    : libgit2-glib is a glib wrapper library around the libgit2 git access library.
description: |
    libgit2-glib is a glib wrapper library around the libgit2 git access library.
patterns   :
    - docs : [/usr/share/doc]
builddeps  :
    - pkgconfig(gio-2.0)
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(libgit2)
    - pkgconfig(libssh2)
    - pkgconfig(openssl)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(python3)
    - gnome-common
    - gtk-doc
    - vala
setup      : |
    %configure --disable-static --enable-python --enable-ssh
build      : |
    %make
install    : |
    %make_install
