name       : libgit2-glib
version    : 0.24.3
release    : 20
source     :
    - http://ftp.acc.umu.se/pub/GNOME/sources/libgit2-glib/0.24/libgit2-glib-0.24.3.tar.xz : 0c4f781d293a57758a81d67e22964e78389f7a4e860ac37c86788a763a625969
license    : LGPL-2.1
component  : programming.library
summary    : libgit2-glib is a glib wrapper library around the libgit2 git access library.
description: |
    libgit2-glib is a glib wrapper library around the libgit2 git access library.
patterns   :
    - docs : [/usr/share/doc]
builddeps  :
    - pkgconfig(gio-2.0)
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(libgit2)
    - pkgconfig(libssh2)
    - pkgconfig(openssl)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(python-3.5)
    - gnome-common
    - gtk-doc
    - vala
setup      : |
    %configure --disable-static --enable-python --enable-ssh
build      : |
    %make
install    : |
    %make_install
