name       : libgit2-glib
version    : 0.26.0
release    : 23
source     :
    - https://ftp.acc.umu.se/pub/GNOME/sources/libgit2-glib/0.26/libgit2-glib-0.26.0.tar.xz : 06b16cfcc3a53d9804858618d690e5509e9af2e2245b75f0479cadbbe39745c3
license    : LGPL-2.1
component  : programming.library
summary    : libgit2-glib is a glib wrapper library around the libgit2 git access library.
description: |
    libgit2-glib is a glib wrapper library around the libgit2 git access library.
patterns   :
    - docs : [/usr/share/doc]
builddeps  :
    - pkgconfig(gio-2.0)
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(libgit2)
    - pkgconfig(libssh2)
    - pkgconfig(openssl)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(python-3.5)
    - gnome-common
    - gtk-doc
    - vala
setup      : |
    %configure --disable-static --enable-python --enable-ssh
build      : |
    %make
install    : |
    %make_install
