name       : libgit2-glib
version    : 0.24.0
release    : 18
source     :
    - http://ftp.gnome.org/pub/GNOME/sources/libgit2-glib/0.24/libgit2-glib-0.24.0.tar.xz : d616c268821c28ff8dc1a6419dbf8555fa48e31dc6509c10f5151be7690f4845
license    : LGPL-2.1
component  : programming.library
summary    : libgit2-glib is a glib wrapper library around the libgit2 git access library.
description: |
    libgit2-glib is a glib wrapper library around the libgit2 git access library.
patterns   :
    - docs : [/usr/share/doc]
builddeps  :
    - pkgconfig(gio-2.0)
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(libgit2)
    - pkgconfig(libssh2)
    - pkgconfig(openssl)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(python-3.5)
    - gnome-common
    - gtk-doc
    - vala
setup      : |
    %configure --disable-static --enable-python --enable-ssh
build      : |
    %make
install    : |
    %make_install
