name       : libgit2-glib
version    : 0.22.8
release    : 6
source     :
    - http://ftp.gnome.org/pub/gnome/sources/libgit2-glib/0.22/libgit2-glib-0.22.8.tar.xz : 05c9453b195f1af0df2a5d8bc71472c9fb26d14bb8fbb5b688ad1b8ef7a30959
license    : LGPL-2.1
summary    : libgit2-glib is a glib wrapper library around the libgit2 git access library.
description: |
    libgit2-glib is a glib wrapper library around the libgit2 git access library.
libsplit : no
patterns :
    - docs: [/usr/share/doc]
builddeps  :
    - pkgconfig(gio-2.0)
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(libgit2)
    - pkgconfig(openssl)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(python-3.4)
setup      : |
    %configure --disable-static --enable-python --enable-ssh
build      : |
    %make
install    : |
    %make_install

    # Move the docs
    mkdir -p $installdir/usr/share/doc/
    mv $installdir/usr/share/gtk-doc/html/libgit2-glib-1.0 $installdir/usr/share/doc/
    rm -rf $installdir/usr/share/gtk-doc
