name       : libgit2-glib
version    : 0.28.0.1
release    : 32
source     :
    - https://github.com/GNOME/libgit2-glib/archive/v0.28.0.1.tar.gz : c9dd1333ae664f21cec05196cd052169fcd819d6ad8e40e3b9914ef240801408
license    : LGPL-2.1-or-later
component  : programming.library
summary    : libgit2-glib is a glib wrapper library around the libgit2 git access library.
description: |
    libgit2-glib is a glib wrapper library around the libgit2 git access library.
patterns   :
    - docs : [/usr/share/doc]
builddeps  :
    - pkgconfig(gio-2.0)
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(libgit2)
    - pkgconfig(libssh2)
    - pkgconfig(openssl)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(python3)
    - gnome-common
    - gtk-doc
    - vala
setup      : |
    %meson_configure -Dgtk_doc=true
build      : |
    %ninja_build
install    : |
    %ninja_install
    mv $installdir/usr/share/vala $installdir/usr/share/vala-0.46
