name       : libgit2-glib
version    : 0.24.2
release    : 19
source     :
    - http://ftp.acc.umu.se/pub/GNOME/sources/libgit2-glib/0.24/libgit2-glib-0.24.2.tar.xz : 6150cffaa93400e553c4d9cf73c3209f0e5889d4511ba5794bcdd174d9d1e349
license    : LGPL-2.1
component  : programming.library
summary    : libgit2-glib is a glib wrapper library around the libgit2 git access library.
description: |
    libgit2-glib is a glib wrapper library around the libgit2 git access library.
patterns   :
    - docs : [/usr/share/doc]
builddeps  :
    - pkgconfig(gio-2.0)
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(libgit2)
    - pkgconfig(libssh2)
    - pkgconfig(openssl)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(python-3.5)
    - gnome-common
    - gtk-doc
    - vala
setup      : |
    %configure --disable-static --enable-python --enable-ssh
build      : |
    %make
install    : |
    %make_install
