name       : libgit2-glib
version    : 0.22.8
release    : 12
source     :
    - https://github.com/GNOME/libgit2-glib/archive/v0.22.8.tar.gz : cfb84eef25ecfa853149245f095407f7eaf49e2a9d51c2d1451801766c687c42
license    : LGPL-2.1
summary    : libgit2-glib is a glib wrapper library around the libgit2 git access library.
description: |
    libgit2-glib is a glib wrapper library around the libgit2 git access library.
libsplit : no
patterns :
    - docs: [/usr/share/doc]
builddeps  :
    - pkgconfig(gio-2.0)
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(libgit2)
    - pkgconfig(libssh2)
    - pkgconfig(openssl)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(python-3.4)
    - gnome-common
    - gtk-doc
    - vala
setup      : |
    NOCONFIGURE=1 ./autogen.sh
    %configure --disable-static --enable-python --enable-ssh
build      : |
    %make
install    : |
    %make_install
