name       : libgit2-glib
version    : 0.25.0
release    : 22
source     :
    - https://ftp.acc.umu.se/pub/GNOME/sources/libgit2-glib/0.25/libgit2-glib-0.25.0.tar.xz : 4a256b9acfb93ea70d37213a4083e2310e59b05f2c7595242fe3c239327bc565
license    : LGPL-2.1
component  : programming.library
summary    : libgit2-glib is a glib wrapper library around the libgit2 git access library.
description: |
    libgit2-glib is a glib wrapper library around the libgit2 git access library.
patterns   :
    - docs : [/usr/share/doc]
builddeps  :
    - pkgconfig(gio-2.0)
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(libgit2)
    - pkgconfig(libssh2)
    - pkgconfig(openssl)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(python-3.5)
    - gnome-common
    - gtk-doc
    - vala
setup      : |
    %configure --disable-static --enable-python --enable-ssh
build      : |
    %make
install    : |
    %make_install
